n1 = int(input('Digite um digito:'))
print('O seu digito foi {}, seu antecessor é {}, e seu sucessor é {}'.format(n1, n1-1, n1+1))
print('Agora vamos ver o dobro, triplo e raiz quadrada de um número.')
n2 = int(input('Digite um númeo:'))
print('Seu digito foi {}.\nO dobro desse número é {}, o triplo é {}, e sua raiz é {}'.format(n2, n2 * 2, n2 * 3, n2 ** (1 / 2)))
